<a href="https://colab.research.google.com/github/ayedsalman/lectures/blob/master/Data_Engineering_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import datetime

dates = pd.date_range('20220101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
#df
df2 = pd.DataFrame({'A': 1.,
	'B': pd.Timestamp('20220102'),
	'C': pd.Series(1, index=list(range(4)), dtype='float32'),
	'D': np.array([3] * 4, dtype='int32'),
	'E': pd.Categorical(["test", "train", "test", "train"]),
  'F': 'foo'})
df


A         B         C         D
2022-01-01 -0.296784  0.012126 -1.278360  1.017883
2022-01-02 -0.626354 -0.383817  0.770903 -0.095194
2022-01-03 -0.266815 -1.260031  0.699019  0.885900
2022-01-04  1.924754  0.276715 -0.482355  0.595216
2022-01-05  0.849145 -0.920118  0.205201  1.389908
2022-01-06 -0.622100 -0.403640  0.928309  0.402327

In [ ]:
df2
df.to_numpy()
df2.to_numpy()
df.sort_index(axis=1, ascending=False)
df.sort_values(by='D')
df.loc['20220102':'20220104', ['A', 'B']]

A         B
2022-01-02 -0.626354 -0.383817
2022-01-03 -0.266815 -1.260031
2022-01-04  1.924754  0.276715

The Problem: What are the roots of the function: f(x) = -2x³+7x²-20x + 6?

In [ ]:
import numpy as np
c=[-2,7,-20,6]
np.roots(c)

array([1.58217509+2.53665299j, 1.58217509-2.53665299j,
       0.33564982+0.j        ])

The Problem: Using python calculate the first derivative of the function: f(x)=4x³+12x-7:

In [ ]:
from sympy import *
x,f=symbols("x f")
init_printing()
f=4*x**3+12*x-7
diff(f,x)

The Problem: Calculate the indefinite integral of the function:
f’(x) = 4x³+12x+7;

In [ ]:
from sympy import *
x,f=symbols("x f")
init_printing()
f=4*x**3+12*x-7
integrate(f,x)

The Problem: Using python, solve the following linear system:

5x+y+3z=76 

-x+2y+5z=35

4x-5y+z=22

In [ ]:
import numpy as np
A = np.array([[5, 1, 3], [-1, 2, 5], [4, -5, 1]])
b = np.array([76, 35, 22])
x = np.linalg.solve(A,b)
print(x)

[10.  5.  7.]


The Problem: Using Python, compute integral of f(x) = x³+cos(x) in a range [0,3]:

In [ ]:
from sympy import *
x,f=symbols("x f")
init_printing()
f=x**3+cos(x)
integrate(f,(x,0,3))

The problem: use python to interpolates the points: 
A(1,5), B(3,4), C(5,9) and D(9,11):

In [ ]:
from scipy.interpolate import *
x=[1,3,5,9]
y=[5,4,9,11]
f=lagrange(x,y)
print(f)

         3         2
-0.1354 x + 1.969 x - 6.615 x + 9.781


The Problem: Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.

In [ ]:
a = int(input("Input an integer : "))
n1 = int( "%s" % a )
n2 = int( "%s%s" % (a,a) )
n3 = int( "%s%s%s" % (a,a,a) )
print (n1+n2+n3)

Input an integer : 1
123


In [ ]:
word = "python"
print(word[:7])

a = ['a', 'b', 'c']
len(a)

python


3

Difference between Numpy Array and Python List

In [ ]:
import numpy as np

L3 = [True, "2", 3.0, 4]
L4 = [type(item) for item in L3]
L5 = np.array([1,2,3,4])
L6 = [type(item) for item in L5]
print(L3, L4)
print(L5, L6)

[True, '2', 3.0, 4] [<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]
[1 2 3 4] [<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>]


In [ ]:
import array
L = list(range(10))
A = array.array('i', L)
A

np.random.random((3, 3))

array([[0.56095314, 0.00250048, 0.32890303],
       [0.35800966, 0.25109381, 0.04615576],
       [0.75564032, 0.68961722, 0.13601244]])

In [ ]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(4, 2, 5)) # Three-dimensional array
print(x1, x2)
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


[5 0 3 3 7 9] [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x3 ndim:  3
x3 shape: (4, 2, 5)
x3 size:  40


Slicing 

In [ ]:
x=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[::2]

x2=np.array([[12, 5, 2, 4],
[ 7, 6, 8, 8],
[ 1, 6, 7, 7]])
x2[:2, :3] # two rows, three columns

x2[:, 0] # mixing slicing and indexing; first column in x2


array([12,  7,  1])

In [ ]:
import numpy as np
grid = np.arange(16).reshape((4, 4))
left, right = np.hsplit(grid, 2)
np.vsplit(grid, np.array([3, 6]))
#print(left)
#print(right)



[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([], shape=(0, 4), dtype=int64)]

Aggregation Functions

In [ ]:
import numpy as np
heights = np.array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173, 174, 183, 
                    183, 168, 170, 178, 182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188, 182, 185])
print(heights)

print("Mean height: ", heights.mean())
print("Standard deviation:", heights.std())
print("Minimum height: ", heights.min())
print("Maximum height: ", heights.max())

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]
Mean height:  179.73809523809524
Standard deviation: 6.931843442745892
Minimum height:  163
Maximum height:  193


Broadcasting 

In [ ]:
import numpy as np

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
print(a)
print(a + b) # normal vectorized operation
print(a+ 5) # broadcasting scalar into 1-D array

M = np.ones((3, 3))
print(M+a) # broadcasting 1-D array into 2-D array

[0 1 2]
[5 6 7]
[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
#Broadcasting along both dimensions for both vectors
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)
a + b


[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Simple Python exercises

In [ ]:
# point is an (x, y) tuple
point = (1,0)
print(point)
match point:
    case (0, 0):
        print("Origin")
    case (0, y):
        print(f"Y={y}")
    case (x, 0):
        print(f"X={x}")
    case (x, y):
        print(f"X={x}, Y={y}")
    case _:
        raise ValueError("Not a point")

SyntaxError: ignored

In [ ]:
!python --version
a=(4,8)
b=(4,5)
if (a>b):print("a is bigger")
else: print("b is bigger")

# write Fibonacci series up to n
def fib(n):    
     """Print a Fibonacci series up to n."""
     x=a, b = 0, 1
     print(x,a,b)
     while a < n:
       print(a, end=' ')
       a, b = b, a+b
       print()

# Now call the function we just defined:
fib(2000)



Python 3.7.12
a is bigger
(0, 1) 0 1
0 
1 
1 
2 
3 
5 
8 
13 
21 
34 
55 
89 
144 
233 
377 
610 
987 
1597 


In [ ]:
def ask_ok(prompt, retries=4, reminder='Please try again!'):
    while True:
        ok = input(prompt)
        if ok in ('y', 'ye', 'yes'):
            return True
        if ok in ('n', 'no', 'nop', 'nope'):
            return False
        retries = retries - 1
        if retries < 0:
            raise ValueError('invalid user response')
        print(reminder)

ask_ok("are you ok?")

are you ok?no


False

In [ ]:
!pip install transformers
!pip install transformers datasets
!pip install Tensorflow

import torch
from transformers import XLMRobertaTokenizer
from transformers import AutoTokenizer, AutoModel, AutoModelForMaskedLM
from transformers import pipeline





#tokenizer = AutoTokenizer.from_pretrained("asafaya/bert-base-arabic")
#model = AutoModelForMaskedLM.from_pretrained("asafaya/bert-base-arabic")

In [ ]:
#!pip install Tensorflow
#tokenizer = AutoTokenizer.from_pretrained("asafaya/bert-base-arabic")
#model = AutoModelForMaskedLM.from_pretrained("asafaya/bert-base-arabic")
classifier = pipeline(model="asafaya/bert-base-arabic")

Downloading:   0%|          | 0.00/0.98k [00:00<?, ?B/s]

In [ ]:
classifier("الله هو [MASK] كل شئ")

[{'score': 0.1769830882549286,
  'sequence': 'الله هو الخالق كل شي',
  'token': 13329,
  'token_str': 'الخالق'},
 {'score': 0.11637908965349197,
  'sequence': 'الله هو خالق كل شي',
  'token': 25830,
  'token_str': 'خالق'},
 {'score': 0.08249117434024811,
  'sequence': 'الله هو كل شي',
  'token': 1,
  'token_str': '[UNK]'},
 {'score': 0.06661193072795868,
  'sequence': 'الله هو المالك كل شي',
  'token': 13314,
  'token_str': 'المالك'},
 {'score': 0.05531790107488632,
  'sequence': 'الله هو مصدر كل شي',
  'token': 5171,
  'token_str': 'مصدر'}]

In [ ]:
import numpy as np




# create float array
np.array([1, 2, 3, 4], dtype='float32')
print(np.arange(0,20,2),  np.array(range(0, 20, 2)))
np.arange(5) / np.arange(1, 6)



[ 0  2  4  6  8 10 12 14 16 18] [ 0  2  4  6  8 10 12 14 16 18]


array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [ ]:
import numpy as np
grid = np.arange(16).reshape((4, 4))
upper, lower, last = np.vsplit(grid, [2,3])
print(upper)
print(lower)
print(last)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


In [ ]:
import numpy as np
import pandas as pd

population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}

population = pd.Series(population_dict)
population['California']



38332521

In [ ]:
import numpy as np
import pandas as pd

area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}

area = pd.Series(area_dict)
population = pd.Series(population_dict)
states = pd.DataFrame({'population': population,
'area': area})
states
#states.columns
#pd.date_range(start='2018-04-24', end='2018-04-30', periods=5)
states.sort_values(by=['area'], ascending=True)

population    area
New York      19651127  141297
Illinois      12882135  149995
Florida       19552860  170312
California    38332521  423967
Texas         26448193  695662

In [ ]:
import numpy as np
import pandas as pd
import datetime
np.random.seed(0)
dates = pd.date_range('20220101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df.sort_values(by='B', ascending=True)
print(df)
df.loc['20220101':'20220104', 'B':'D']

                   A         B         C         D
2022-01-01  1.764052  0.400157  0.978738  2.240893
2022-01-02  1.867558 -0.977278  0.950088 -0.151357
2022-01-03 -0.103219  0.410599  0.144044  1.454274
2022-01-04  0.761038  0.121675  0.443863  0.333674
2022-01-05  1.494079 -0.205158  0.313068 -0.854096
2022-01-06 -2.552990  0.653619  0.864436 -0.742165


B         C         D
2022-01-01  0.400157  0.978738  2.240893
2022-01-02 -0.977278  0.950088 -0.151357
2022-01-03  0.410599  0.144044  1.454274
2022-01-04  0.121675  0.443863  0.333674

In [ ]:
df2 = pd.DataFrame({'A': 1.,
	'B': pd.Timestamp('20220102'),
	'C': pd.Series(1, index=list(range(4)), dtype='float32'),
	'D': np.array([3] * 4, dtype='int32'),
	'E': pd.Categorical(["test", "train", "test", "train"]),
'F': 'foo'})
df2.index =['1','2','5','A']
df2

A          B    C  D      E    F
1  1.0 2022-01-02  1.0  3   test  foo
2  1.0 2022-01-02  1.0  3  train  foo
5  1.0 2022-01-02  1.0  3   test  foo
A  1.0 2022-01-02  1.0  3  train  foo

In [ ]:
import numpy as np
import pandas as pd

area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
'Illinois': 149995})

pop = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})

data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [ ]:
# Broadcasting
import numpy as np

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
print(a)
print(a + b) # normal vectorized operation
print(a+ 5) # broadcasting scalar into 1-D array

M = np.ones((3, 3))
print(M+a) # broadcasting 1-D array into 2-D array


[0 1 2]
[5 6 7]
[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
#Broadcasting

a = np.arange(8).reshape((1, 8))
b = np.arange(24).reshape(3,8)
#np.arange(4)[:, np.newaxis]
print(a)
print(b)
b + a


[[0 1 2 3 4 5 6 7]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 8, 10, 12, 14, 16, 18, 20, 22],
       [16, 18, 20, 22, 24, 26, 28, 30]])

In [ ]:
import numpy as np
import pandas as pd

def make_df(cols, ind):
  data = {c: [str(c) + str(i) for i in ind]   for c in cols}
  return pd.DataFrame(data, ind)

df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1); print(df2); print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [ ]:
import numpy as np
import pandas as pd

df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
'food': ['fish', 'beans', 'bread']},
columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
'drink': ['Pepsi', 'Water']},
columns=['name', 'drink'])
print(pd.merge(df6, df7, how='outer'))
print(pd.merge(df6, df7, how='inner'))
print(pd.merge(df6, df7, how='left'))
print(pd.merge(df6, df7, how='right'))


     name   food  drink
0   Peter   fish    NaN
1    Paul  beans    NaN
2    Mary  bread  Pepsi
3  Joseph    NaN  Water
   name   food  drink
0  Mary  bread  Pepsi
    name   food  drink
0  Peter   fish    NaN
1   Paul  beans    NaN
2   Mary  bread  Pepsi
     name   food  drink
0    Mary  bread  Pepsi
1  Joseph    NaN  Water


In [ ]:
import pandas as pd

student_dict = {'Name': ['Joe', 'Nat', 'Harry','Jack','Jose','Jill','Rose'],
                'Age': [20, 21, 19,17,18,19,17],
                'Marks': [85.10, 77.80, 91.54,72,87.9,90,72]}

# create DataFrame from dict
student_df = pd.DataFrame(student_dict)

# display first 5 rows
print(student_df.head())
# display last 5 rows
print(student_df.tail())

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
3   Jack   17  72.00
4   Jose   18  87.90
    Name  Age  Marks
2  Harry   19  91.54
3   Jack   17  72.00
4   Jose   18  87.90
5   Jill   19  90.00
6   Rose   17  72.00


In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'], 'data': range(6)}, columns=['key', 'data'])
#print(df)
df.groupby('key')


df.groupby('key')['data']


df.groupby('key')['data'].sum()


key
A    3
B    5
C    7
Name: data, dtype: int64

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'First Name': ['Salman', 'Suha', 'Riya', 'Mohammed', 'Sadeq', ],
                   'Last Name': ['Ahmad', 'Mohammed', 'Jasim', 'Basim', 'Khalid'],
                   'Type': ['Full-time Employee', 'Intern', 'Full-time Employee', 
                            'Part-time Employee', 'Full-time Employee'],
                   'Department': ['Administration', 'Technical', 'Administration', 
                                  'Technical', 'Management'],
                   'YoE': [2, 3, 5, 7, 6],
                   'Salary': [20000, 5000, 10000, 10000, 20000]})

df
output = pd.pivot_table(data=df, 
                        index=['Type'], 
                        columns=['Department'], 
                        values='Salary',
                        aggfunc=['sum', 'mean', 'count'])
output

sum                                mean  \
Department         Administration Management Technical Administration   
Type                                                                    
Full-time Employee        30000.0    20000.0       NaN        15000.0   
Intern                        NaN        NaN    5000.0            NaN   
Part-time Employee            NaN        NaN   10000.0            NaN   

                                                 count                       
Department         Management Technical Administration Management Technical  
Type                                                                         
Full-time Employee    20000.0       NaN            2.0        1.0       NaN  
Intern                    NaN    5000.0            NaN        NaN       1.0  
Part-time Employee        NaN   10000.0            NaN        NaN       1.0

In [ ]:
import pandas as pd
import numpy as np

data = ['peter', 'Paul', None, 'MARY', 'gUIDO']

names = pd.Series(data)
names.str.capitalize()

0    Peter
1     Paul
2     None
3     Mary
4    Guido
dtype: object

In [ ]:
import pandas as pd
fri = pd.Timestamp("2018-01-05")
fri.day_name()

# Add 1 day
sat = fri + pd.Timedelta("1 day")
sat.day_name()

# Add 3 business day (Friday --> Monday)
wed = fri + pd.offsets.BDay() * 3
wed.day_name()

idx =pd.date_range("1/1/2022", freq="M", periods=3)
ts= pd.Series(range(len(idx)),index=idx)
ts

2022-01-31    0
2022-02-28    1
2022-03-31    2
Freq: M, dtype: int64

In [ ]:
import pandas as pd 

# data sources link
excel_another_dir = './test.xlsx'

# read data from excel file

df_read_excel = pd.read_excel(excel_another_dir)
df_read_excel.head()

n  2n-1  2n^2-2n+5
0 -1    -3          9
1  0    -1          5
2  1     1          5
3  2     3          9
4  3     5         17

In [ ]:
from io import StringIO
import numpy as np
import pandas as pd

data = ('col1,col2,col3\n'
 'a,b,1\n'
 'a,b,2\n'
 'c,d,3')
print(pd.read_csv(StringIO(data)))
pd.read_csv(StringIO(data), skiprows=lambda x: x % 2 != 0)
pd.read_csv(StringIO(data), usecols=lambda x: x.upper() in ['col1','COL2', 'COL3'])

  col1 col2  col3
0    a    b     1
1    a    b     2
2    c    d     3


col2  col3
0    b     1
1    b     2
2    d     3

In [ ]:
import pandas as pd 

# local data sources link
#html_file = './Dataset/table.html'

#df_html_file = pd.DataFrame(pd.read_html(html_file)[0])

# website data sources link
html_url = 'https://en.wikipedia.org/wiki/Ahmadi_Governorate'

page=pd.read_html(html_url)
len(page)
df_html_url = pd.DataFrame(page[0])
print(df_html_url)

                          Ahmadi Governorate  Jamsher  \
0                                         Governorate   
1               Map of Kuwait with Ahmadi highlighted   
2   Coordinates (Ahmadi): .mw-parser-output .geo-d...   
3                                             Country   
4                                           Districts   
5                                                Area   
6                                             • Total   
7                           Population (June 2014)[1]   
8                                             • Total   
9                                           • Density   
10                                          Time zone   
11                                      ISO 3166 code   

                        Ahmadi Governorate  Jamsher.1  
0                                         Governorate  
1               Map of Kuwait with Ahmadi highlighted  
2   Coordinates (Ahmadi): .mw-parser-output .geo-d...  
3                                 

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
'data': range(6)}, columns=['key', 'data'])
df.groupby('key').sum()


data
key      
A       3
B       5
C       7

In [ ]:
pd.Series(pd.date_range("15/11/2022", freq="BM", periods=6))


0   2022-11-30
1   2022-12-30
2   2023-01-31
3   2023-02-28
4   2023-03-31
5   2023-04-28
dtype: datetime64[ns]

# New Section

In [ ]:
# using scipy to solve linear system of equations

from scipy import linalg
import numpy as np

A = np.array([[1, 3, 5], [2,5,1], [2, 3, 8]])
print(A)
b = np.array([[10], [8],[3]])
print(b)
x_slow=linalg.inv(A).dot(b)  # slow
A.dot(linalg.inv(A).dot(b)) - b  # check
print(x_slow)
x_fast= np.linalg.solve(A, b)  # fast
print(x_fast)
# you can check if your solution is right then you should have array of zeros
A.dot(np.linalg.solve(A, b)) - b  # check

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[10]
 [ 8]
 [ 3]]
[[-9.28]
 [ 5.16]
 [ 0.76]]
[[-9.28]
 [ 5.16]
 [ 0.76]]


array([[ 0.00000000e+00],
       [-1.77635684e-15],
       [-1.77635684e-15]])

In [ ]:
import numpy as np
from sklearn import metrics

print("%.3f" % metrics.homogeneity_score ([0, 0, 1, 0, 0, 1], [0, 0, 1, 1, 0, 1]))
print("%.3f" % metrics.completeness_score ([0, 0, 1, 0, 0, 1], [0, 0, 1, 1, 0, 1]))
print("%.3f" % metrics.v_measure_score ([0, 0, 1, 0, 0, 1], [0, 0, 1, 1, 0, 1]))

0.500
0.459
0.479
